version: '3.9'

services:
  rabbitmqtestdb:
    container_name: rabbitmqtestdb
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - rabbitmqtestdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password1*
      - POSTGRES_DB=rabbitmqtestdb
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbitmqtest.api:
    container_name: rabbitmqtest.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
      - rabbitmqtestdb