version: '3.9'

services:
  rabbitmqtestdb:
    image: postgres
  rabbitmq:
    image: rabbitmq:3.9.0-management
  rabbitmqtest.api:
    image: rabbitmqtest_api_image
    build:
      context: .
      dockerfile: Dockerfile
volumes:
    rabbitmqtestdb_volume: