// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RabbitMQTest.Context;

#nullable disable

namespace RabbitMQTest.Migrations
{
    [DbContext(typeof(BosMessageQueueDbContext))]
    partial class BosMessageQueueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RabbitMQTest.Models.DataModels.RequestLogs", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("RowId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("RowId"), 1L, null, null, null, null, null);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Description");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("LogDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Request");

                    b.Property<string>("Response")
                        .HasColumnType("TEXT")
                        .HasColumnName("Response");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Url");

                    b.HasKey("RowId")
                        .HasName("pk_row_id");

                    b.ToTable("RequestLogs", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
